name: Automatic build

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run:  |
        sudo apt update
        sudo apt install libssl-dev libluajit-5.1-dev libcurl4-openssl-dev zlib1g-dev libsdl2-dev pkg-config ccache python3-pip git libfftw3-dev #libnghttp2-dev libidn2-dev librtmp-dev libpsl-dev libgssapi-krb5-2 libkrb5-dev libk5crypto3 libcom-err2 libldap2-dev libxcb1-dev libxau-dev libxdmcp-dev libgmp-dev libgnutls28-dev libnettle6
        sudo pip3 install meson ninja
    - name: Build for x86_64
      run: ./build.sh

    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: false
        title: "Nightly Build"
        files: |
          *.AppImage
          *.zsync
          chrootdir/*.AppImage
          chrootdir/*.zsync
